export const env = {
  BASE_URL: process.env.NEXT_PUBLIC_BASE_URL,
  BACKEND_URL: process.env.NEXT_PUBLIC_BACKEND_URL,
  APPWRITE_URL: process.env.NEXT_PUBLIC_APPWRITE_URL,
  APPWRITE_PROJECT_ID: process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID,
  RAZORPAY_ID_KEY: process.env.NEXT_PUBLIC_RAZORPAY_ID_KEY,
};
